version: '3.8'

services:
  anomaly-detection:
    build: .
    volumes:
      - .:/app
      - ./outputs:/app/outputs
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - LLM_PROVIDER=${LLM_PROVIDER}
      - LLM_MODEL=${LLM_MODEL}
    deploy:
      resources:
        limits:
          memory: 4G